update the Profile-Head-of-Resume
Arc-i-Tech-PlayArea/My-Profile pull request #27
Opened 2024-08-14 17:56 UTC by ajstyle2410

add the  static image and add name ,email ,contact and address
closes #18

2024-08-16 13:00 UTC, dipikakoli26 commented on index.html
> +                  <p class="text-lowercase">ajdeshmukh241@gmail.com</p>
The email link should be open their default email person.

2024-08-16 13:02 UTC, dipikakoli26 commented on index.html
> +                  id="profile-pic"
Its Better to add your own photo at the profile.

2024-08-16 13:05 UTC, dipikakoli26 requested changes
@ajstyle2410  Change code as per comments.

2024-08-22 14:24 UTC, dipikakoli26 commented
@ajstyle2410 Reslove conflict.

2024-08-22 16:44 UTC, ajstyle2410 commented
conflict is resolved

2024-08-24 06:25 UTC, dipikakoli26 commented on index.html
> +                  <p class="text-lowercase">ajdeshmukh241@gmail.com</p>
Make this email validate as soon as possible

2024-08-24 06:26 UTC, dipikakoli26 requested changes
Change as per suggested comment.

2024-08-28 05:18 UTC, merged