Extra Curricular User Story
Arc-i-Tech-PlayArea/My-Profile pull request #32
Opened 2024-08-23 03:04 UTC by ajstyle2410

marge courses and certification and  achievements tasks 
closes #4

2024-08-29 18:32 UTC, ajayg2808 requested changes
Do changes as requested.

2024-08-29 18:32 UTC, ajayg2808 commented on css/index.css
> +body {
Do not add body styling, It might impact other body tags.

2024-08-29 18:32 UTC, ajayg2808 commented on css/index.css
> +}
Do not use tag selector, instead prefer class/ id selectors

2024-08-29 18:32 UTC, ajayg2808 commented on index.html
> +    <div class="resume-container">
Both sections are independent, Do not enclose them in a single <div>. It is problematic for other sections.

2024-08-29 18:32 UTC, ajayg2808 commented on index.html
> +            <h2>Courses and Certificates</h2>
Section title should be **"Courses and Certifications"**

2024-08-29 18:32 UTC, ajayg2808 commented on index.html
> +                <li>Developed a Library Management System using Java, JSP & Servlets, MySQL</li>
These are not an achievements.

2024-08-30 08:20 UTC, ajstyle2410 commented on css/index.css
> +}
remove the selector tag

2024-08-30 08:21 UTC, ajstyle2410 commented on index.html
> +    <div class="resume-container">
remove the  resume-container class

2024-08-30 08:22 UTC, ajstyle2410 commented
@ajayg2808 
update the #32  please check it

2024-08-30 08:34 UTC, ajayg2808 requested changes
Do changes as requested

2024-08-30 08:34 UTC, ajayg2808 commented on css/index.css
> +.courses-certificates h2, .achievements  h2 {
Create a single class instead.

2024-08-30 08:34 UTC, ajayg2808 commented on css/index.css
> +.courses-certificates ul, .achievements ul {
Create a single class

2024-08-30 08:34 UTC, ajayg2808 commented on css/index.css
> +.courses-certificates ul li, .achievements ul li {
Create a single class

2024-08-30 08:34 UTC, ajayg2808 commented on index.html
> +            <h2>Courses and Certificates</h2>
Correct section title as requested in previous review

2024-08-30 09:19 UTC, ajstyle2410 commented on index.html
> +            <h2>Courses and Certificates</h2>
rename the title name

2024-08-30 09:27 UTC, ajstyle2410 commented on css/index.css
> +.courses-certificates h2, .achievements  h2 {
Create a single class

2024-08-30 09:28 UTC, ajstyle2410 commented on index.html
> +            <h2>Courses and Certificates</h2>
update the title

2024-08-30 09:28 UTC, ajstyle2410 commented on css/index.css
> +.courses-certificates ul li, .achievements ul li {
update the in single class

2024-08-31 06:50 UTC, ajayg2808 requested changes

2024-08-31 06:50 UTC, ajayg2808 commented on index.html
> +                <li>Completed a Java Full-Stack Development course</li>
This is not an achievement.

2024-08-31 06:50 UTC, ajayg2808 commented on index.html
> +                <li>Developed a Library Management System using Java, JSP & Servlets, MySQL</li>
This is not an achievement

2024-08-31 07:51 UTC, ajstyle2410 commented on index.html
> +                <li>Completed a Java Full-Stack Development course</li>
update the achivements

2024-08-31 07:51 UTC, ajstyle2410 commented on index.html
> +                <li>Developed a Library Management System using Java, JSP & Servlets, MySQL</li>
update the list

2024-08-31 15:14 UTC, ajayg2808 approved these changes

2024-08-31 15:14 UTC, ajayg2808 commented on css/index.css
> +
Padding and margins are not responsive

2024-08-31 15:14 UTC, ajayg2808 commented on index.html
Code formatting is not correct

2024-08-31 15:15 UTC, merged