10 miscellaneous
Arc-i-Tech-PlayArea/My-Profile pull request #42
Opened 2024-08-31 15:13 UTC by priyapal2000

In this epic have two task that is menu bar and career object.
closes #10

2024-09-01 18:44 UTC, ajayg2808 requested changes
Refer for menu links: https://www.w3schools.com/html/html_links_bookmarks.asp

2024-09-01 18:44 UTC, ajayg2808 commented on css/index.css
> +p {
Do not use tag/ element selectors

2024-09-01 18:44 UTC, ajayg2808 commented on css/index.css
> +body,
Do not add CSS for body tag

2024-09-01 18:44 UTC, ajayg2808 commented on index.html
> +                <li><a href="#">Contact Me</a></li>
Add menu links. Add section ID's as reference link.

2024-09-02 09:33 UTC, priyapal2000 commented on css/index.css
> +body,
Remove the body tag in CSS file is done.

2024-09-02 09:46 UTC, priyapal2000 commented on css/index.css
> +p {
changes done selectors tag.

2024-09-03 04:06 UTC, priyapal2000 commented on index.html
> +                <li><a href="#">Contact Me</a></li>
Successfully added id's .

2024-09-03 18:15 UTC, ajayg2808 approved these changes
Always follow code formatting and naming conventions.

2024-09-03 18:15 UTC, merged